### ISSUE TITLE
Win 10, OpenFaceOffline.exe, model file not found

### ISSUE THREAD

**Issue by dpucsd** [TadasBaltrusaitis/OpenFace#434]
after trying to open the video file, I get the error message in this screenshot...
![of error 2](https://user-images.githubusercontent.com/21962979/39962914-53d578f2-5612-11e8-86e3-19f0c09314e1.png)

**Comment by NumesSanguis** [comment]
"For CE-CLM landmark detector to work you need to download additional model files, this can be done by executing the download_models.ps1 PowerShell script. For more details on model download see - https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-acquisition"
[https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation](https://github.com/TadasBaltrusaitis/OpenFace/wiki/Windows-Installation)

If you right click [download_models.ps1] and right-click --> select [Run with PowerShell] it works (if you're on Windows 10).

The link [https://github.com/TadasBaltrusaitis/OpenFace/wiki/Model-acquisition] however cannot be accessed and gives an error "You do not have permission to update this wiki. ".

**Comment by elahia** [comment]
@NumesSanguis   i tried for the link and i download the .dat files but i do not know where to put them! actually, i have to put it in lib\local\landmarkdetector\model\patchexperts

but i couldnät find the directory!

**Comment by elahia** [comment]
@NumesSanguis  i find what you mean! i found download_models.ps1 file in the openface directory and execute it as you said
thank you so much

**Comment by TadasBaltrusaitis** [comment]
Can you try opening your video file using `FaceLandmarkVid.exe` or `FeatureExtraction.exe`? I realized that the GUI is not yet very stable in this version. I'm working to identify what is making it crash sometimes.

**Comment by dpucsd** [comment]
[unable to access computer for a couple days ... will test and respond on Sat or Sun]

**Comment by elahia** [comment]
for me i just run download_models.ps1 and then when i checked, it was located in true directories, 
if you want i can explain the overall process in more details, just as a summary...

**Comment by dpucsd** [comment]
sure

**Comment by elahia** [comment]
I encountered this error, but i really don't remember how i fixed it, because there were some other errors too, so I will explain everything, maybe boring for you but helpful for others!

first after downloading and extracting the package of _openfase_master_:
1. run "download_models" by powersell  (right-click on the file with download_models name)
this **automatically** download 4 c++ models and 12 Matlab models and save them in considered folders (may you need to enter a capital Y in the blue window as permission)

2. open "openface" in main directory  by vs2015,

3. in vs2015 set one of 4 executable projects as startup project
4. set x64 in solution platform box (next to solution configuration box)
5. in tutorial its mentioned that compile program by CTR+f5, but for me this caused an error, link1181! so instead I tried for: build -> rebuild solution  then the error solved (@TadasBaltrusaitis  correct me if it is not true)

6. after rebuilding, a version of openfaceoffline will be produced in: "x64/releas" with a dark circle icon

7. run this dark icon 

8. a window will appear that in its first tab, file, you can choose "open webcam" and start playing with it, 

9. after stopping the window (by clicking "stop" in the bottom of the window) a new folder will be created in "x64/releas" which name is "processed",  in this folder 3 files are created for each integration to the webcam, 

10. use these files 

i hope this helps you and others,

**Comment by dpucsd** [comment]
when we run "FaceLandmarkVid.exe TWSTRSSUBJ3trimmed10301130.mp4"
with the .mp4 in the same folder, we get the following output:

Reading the landmark detector/tracker from: model/main_ceclm_general.txt
Reading the landmark detector module from: model\cen_general.txt
Reading the PDM module from: model\pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: model\tris_68.txt....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_0.35_of.dat....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_0.50_of.dat....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_1.00_of.dat....Done
Reading part based module....left_eye_28
Reading the landmark detector/tracker from: model\model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: model\model_eye\clnf_left_synth.txt
Reading the PDM module from: model\model_eye\pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading part based module....right_eye_28
Reading the landmark detector/tracker from: model\model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: model\model_eye\clnf_right_synth.txt
Reading the PDM module from: model\model_eye\pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading the landmark validation module....Done

but no indication that it read in the video file or processed it, and cannot any output file

**Comment by dpucsd** [comment]
Likewise with FeatureExtraction.exe TWSTRSSUBJ3trimmed10301130.mp4:

Reading the landmark detector/tracker from: model/main_ceclm_general.txt
Reading the landmark detector module from: model\cen_general.txt
Reading the PDM module from: model\pdms/In-the-wild_aligned_PDM_68.txt....Done
Reading the Triangulations module from: model\tris_68.txt....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_0.25_of.dat....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_0.35_of.dat....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_0.50_of.dat....Done
Reading the intensity CEN patch experts from: model\patch_experts/cen_patches_1.00_of.dat....Done
Reading part based module....left_eye_28
Reading the landmark detector/tracker from: model\model_eye/main_clnf_synth_left.txt
Reading the landmark detector module from: model\model_eye\clnf_left_synth.txt
Reading the PDM module from: model\model_eye\pdms/pdm_28_l_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/left_ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/left_ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading part based module....right_eye_28
Reading the landmark detector/tracker from: model\model_eye/main_clnf_synth_right.txt
Reading the landmark detector module from: model\model_eye\clnf_right_synth.txt
Reading the PDM module from: model\model_eye\pdms/pdm_28_eye_3D_closed.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/ccnf_patches_1.00_synth_lid_.txt....Done
Reading the intensity CCNF patch experts from: model\model_eye\patch_experts/ccnf_patches_1.50_synth_lid_.txt....Done
Done
Reading the landmark validation module....Done
Reading the AU analysis module from: AU_predictors/main_dynamic_svms.txt
Reading the AU predictors from: AU_predictors\AU_all_best.txt... Done
Reading the PDM from: AU_predictors\In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:AU_predictors\tris_68_full.txt... Done

**Comment by dpucsd** [comment]
ah, sorry, should have looked at the wiki for cmd line args.  

now, when I'm in the directory with the executable, and I run

FeatureExtraction.exe -f "TWSTRSSUBJ3trimmed10301130.mp4"

the last few lines of output are:

Reading the PDM from: AU_predictors\In-the-wild_aligned_PDM_68.txt... Done
Reading the triangulation from:AU_predictors\tris_68_full.txt... Done
Attempting to read from file: TWSTRSSUBJ3trimmed10301130.mp4
Device or file opened
ERROR: could not open the output file:"processed\TWSTRSSUBJ3trimmed10301130_of_details.txt", either the path of the output directory is wrong or you do not have the permissions to write to it

I tried tweaking Windows' permissions for that 'processed' directory but they would not persist

if I use this arg:    -out_dir output

then the last few output lines are:

Reading the triangulation from:AU_predictors\tris_68_full.txt... Done
Attempting to read from file: TWSTRSSUBJ3trimmed10301130.mp4
Device or file opened

but I don't see anything in the "output" folder and there is no other output in the shell

so alternatively I tried in a separate directory that I had created and which contains the .mp4 file this call:


"c:\Program Files\OpenFace_2.0.0_win_x64\FeatureExtraction.exe" -f "TWSTRSSUBJ3trimmed10301130.mp4"

and the last few lines of output look like this:

Reading the triangulation from:c:\Program Files\OpenFace_2.0.0_win_x64\AU_predictors\tris_68_full.txt... Done
Attempting to read from file: TWSTRSSUBJ3trimmed10301130.mp4
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:808)
warning: TWSTRSSUBJ3trimmed10301130.mp4 (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:809)
Failed to open the video file at location: TWSTRSSUBJ3trimmed10301130.mp4

**Comment by dpucsd** [comment]
If, however, in the OpenFace dir, I run

FaceLandmarkVid.exe -f "TWSTRSSUBJ3trimmed10301130.mp4"

then things run and a new window appears showing the video with expected features overlaid.  But I don't see any output file

adding the arg -out_dir output

I still don't see any output file

**Comment by TadasBaltrusaitis** [comment]
FaceLandmarkVid.exe does not produce any output, it is only for visualization purposes, you need to use FeatureExtraction.exe to get output. See https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments

**Comment by dpucsd** [comment]
OK.  So see my second to last comment about the problems when running FeatureExtraction.exe

**Comment by TadasBaltrusaitis** [comment]
The issue seems to be because of permissions to write to the processed folder. Can you try opening the command line as administrator? 

When you execute:
`"c:\Program Files\OpenFace_2.0.0_win_x64\FeatureExtraction.exe" -f "TWSTRSSUBJ3trimmed10301130.mp4"`
What directory do you execute it in, it might not manage to find the input file because it does not know where to find it, try providing the full path name.

**Comment by dpucsd** [comment]
Executed that call in the same directory as the input file, and it worked, as expected.  That is sufficient for our needs.  

As a side note, annoyingly it seems that Windows does not allow even the administrator to have write access to folders under the Program Files tree, and administrator could not even unset the "read only" flag under the folder's permissions.  So the "processed" subdirectory under the OF tree could be a bit misleading as a potential target location for outputs.  Perhaps that is a leftover from testing ?
